name: GabrielleElyse
favicon: null
layout_spectrum: 0.4071099851280451
typography_spectrum: 0.27613523229956627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.610535497777164
  lightness: 0.01603562361560762
  saturation: 0.03973517217673361
  rhythmicContrast: 0.40640139440074563
purpose: []
